# ==============================================================================
# ruff.toml
# ENCLAVE: IMMORTAL_MONTI_FILE_ENCLAVE
# AUTHORIZATION: MONTI^JOHN^CHARLES^MONTI
# DOMAINS: human.johncharlesmonti.com | montiai.com | monti.bio | ATTORNEYMODE.COM
# PURPOSE: Global Workforce Python Linting & Formatting Enforcement
# ==============================================================================

line-length = 99
extend-include = ["*.ipynb", "*.monti"]
force-exclude = true
exclude = [
    ".venv",
    "**/__pycache__",
    "**/node_modules",
    "**/dist",
    "**/build",
    "**/env",
    "**/.ruff_cache",
    "**/.venv",
    "**/.ipynb_checkpoints",
    "**/secrets_baseline"
]

[lint]
exclude = ["__init__.py"]
select = ["C", "D", "E", "F", "I", "W"]
ignore = ["C901", "E501", "E741", "F402", "F823", "D100", "D106"]

[lint.isort]
lines-after-imports = 2
no-sections = true

[lint.per-file-ignores]
"**/*.ipynb" = ["F704"]

[lint.pydocstyle]
convention = "google"

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
